// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	db "github.com/mwhite7112/woodpantry-pantry/internal/db"
	mock "github.com/stretchr/testify/mock"
)

// MockQuerier is an autogenerated mock type for the Querier type
type MockQuerier struct {
	mock.Mock
}

type MockQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQuerier) EXPECT() *MockQuerier_Expecter {
	return &MockQuerier_Expecter{mock: &_m.Mock}
}

// CreateIngestionJob provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateIngestionJob(ctx context.Context, arg db.CreateIngestionJobParams) (db.IngestionJob, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateIngestionJob")
	}

	var r0 db.IngestionJob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateIngestionJobParams) (db.IngestionJob, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateIngestionJobParams) db.IngestionJob); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.IngestionJob)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateIngestionJobParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_CreateIngestionJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIngestionJob'
type MockQuerier_CreateIngestionJob_Call struct {
	*mock.Call
}

// CreateIngestionJob is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateIngestionJobParams
func (_e *MockQuerier_Expecter) CreateIngestionJob(ctx interface{}, arg interface{}) *MockQuerier_CreateIngestionJob_Call {
	return &MockQuerier_CreateIngestionJob_Call{Call: _e.mock.On("CreateIngestionJob", ctx, arg)}
}

func (_c *MockQuerier_CreateIngestionJob_Call) Run(run func(ctx context.Context, arg db.CreateIngestionJobParams)) *MockQuerier_CreateIngestionJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateIngestionJobParams))
	})
	return _c
}

func (_c *MockQuerier_CreateIngestionJob_Call) Return(_a0 db.IngestionJob, _a1 error) *MockQuerier_CreateIngestionJob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_CreateIngestionJob_Call) RunAndReturn(run func(context.Context, db.CreateIngestionJobParams) (db.IngestionJob, error)) *MockQuerier_CreateIngestionJob_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStagedItem provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) CreateStagedItem(ctx context.Context, arg db.CreateStagedItemParams) (db.StagedItem, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for CreateStagedItem")
	}

	var r0 db.StagedItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateStagedItemParams) (db.StagedItem, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.CreateStagedItemParams) db.StagedItem); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.StagedItem)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.CreateStagedItemParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_CreateStagedItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStagedItem'
type MockQuerier_CreateStagedItem_Call struct {
	*mock.Call
}

// CreateStagedItem is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.CreateStagedItemParams
func (_e *MockQuerier_Expecter) CreateStagedItem(ctx interface{}, arg interface{}) *MockQuerier_CreateStagedItem_Call {
	return &MockQuerier_CreateStagedItem_Call{Call: _e.mock.On("CreateStagedItem", ctx, arg)}
}

func (_c *MockQuerier_CreateStagedItem_Call) Run(run func(ctx context.Context, arg db.CreateStagedItemParams)) *MockQuerier_CreateStagedItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.CreateStagedItemParams))
	})
	return _c
}

func (_c *MockQuerier_CreateStagedItem_Call) Return(_a0 db.StagedItem, _a1 error) *MockQuerier_CreateStagedItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_CreateStagedItem_Call) RunAndReturn(run func(context.Context, db.CreateStagedItemParams) (db.StagedItem, error)) *MockQuerier_CreateStagedItem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAllPantryItems provides a mock function with given fields: ctx
func (_m *MockQuerier) DeleteAllPantryItems(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAllPantryItems")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_DeleteAllPantryItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAllPantryItems'
type MockQuerier_DeleteAllPantryItems_Call struct {
	*mock.Call
}

// DeleteAllPantryItems is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerier_Expecter) DeleteAllPantryItems(ctx interface{}) *MockQuerier_DeleteAllPantryItems_Call {
	return &MockQuerier_DeleteAllPantryItems_Call{Call: _e.mock.On("DeleteAllPantryItems", ctx)}
}

func (_c *MockQuerier_DeleteAllPantryItems_Call) Run(run func(ctx context.Context)) *MockQuerier_DeleteAllPantryItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQuerier_DeleteAllPantryItems_Call) Return(_a0 error) *MockQuerier_DeleteAllPantryItems_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_DeleteAllPantryItems_Call) RunAndReturn(run func(context.Context) error) *MockQuerier_DeleteAllPantryItems_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePantryItem provides a mock function with given fields: ctx, id
func (_m *MockQuerier) DeletePantryItem(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePantryItem")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockQuerier_DeletePantryItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePantryItem'
type MockQuerier_DeletePantryItem_Call struct {
	*mock.Call
}

// DeletePantryItem is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) DeletePantryItem(ctx interface{}, id interface{}) *MockQuerier_DeletePantryItem_Call {
	return &MockQuerier_DeletePantryItem_Call{Call: _e.mock.On("DeletePantryItem", ctx, id)}
}

func (_c *MockQuerier_DeletePantryItem_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_DeletePantryItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuerier_DeletePantryItem_Call) Return(_a0 error) *MockQuerier_DeletePantryItem_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockQuerier_DeletePantryItem_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockQuerier_DeletePantryItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetIngestionJob provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetIngestionJob(ctx context.Context, id uuid.UUID) (db.IngestionJob, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetIngestionJob")
	}

	var r0 db.IngestionJob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.IngestionJob, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.IngestionJob); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.IngestionJob)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetIngestionJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIngestionJob'
type MockQuerier_GetIngestionJob_Call struct {
	*mock.Call
}

// GetIngestionJob is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) GetIngestionJob(ctx interface{}, id interface{}) *MockQuerier_GetIngestionJob_Call {
	return &MockQuerier_GetIngestionJob_Call{Call: _e.mock.On("GetIngestionJob", ctx, id)}
}

func (_c *MockQuerier_GetIngestionJob_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_GetIngestionJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuerier_GetIngestionJob_Call) Return(_a0 db.IngestionJob, _a1 error) *MockQuerier_GetIngestionJob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetIngestionJob_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.IngestionJob, error)) *MockQuerier_GetIngestionJob_Call {
	_c.Call.Return(run)
	return _c
}

// GetPantryItem provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetPantryItem(ctx context.Context, id uuid.UUID) (db.PantryItem, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetPantryItem")
	}

	var r0 db.PantryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.PantryItem, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.PantryItem); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.PantryItem)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetPantryItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPantryItem'
type MockQuerier_GetPantryItem_Call struct {
	*mock.Call
}

// GetPantryItem is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) GetPantryItem(ctx interface{}, id interface{}) *MockQuerier_GetPantryItem_Call {
	return &MockQuerier_GetPantryItem_Call{Call: _e.mock.On("GetPantryItem", ctx, id)}
}

func (_c *MockQuerier_GetPantryItem_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_GetPantryItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuerier_GetPantryItem_Call) Return(_a0 db.PantryItem, _a1 error) *MockQuerier_GetPantryItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetPantryItem_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.PantryItem, error)) *MockQuerier_GetPantryItem_Call {
	_c.Call.Return(run)
	return _c
}

// GetStagedItem provides a mock function with given fields: ctx, id
func (_m *MockQuerier) GetStagedItem(ctx context.Context, id uuid.UUID) (db.StagedItem, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetStagedItem")
	}

	var r0 db.StagedItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (db.StagedItem, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) db.StagedItem); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(db.StagedItem)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_GetStagedItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStagedItem'
type MockQuerier_GetStagedItem_Call struct {
	*mock.Call
}

// GetStagedItem is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockQuerier_Expecter) GetStagedItem(ctx interface{}, id interface{}) *MockQuerier_GetStagedItem_Call {
	return &MockQuerier_GetStagedItem_Call{Call: _e.mock.On("GetStagedItem", ctx, id)}
}

func (_c *MockQuerier_GetStagedItem_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockQuerier_GetStagedItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuerier_GetStagedItem_Call) Return(_a0 db.StagedItem, _a1 error) *MockQuerier_GetStagedItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_GetStagedItem_Call) RunAndReturn(run func(context.Context, uuid.UUID) (db.StagedItem, error)) *MockQuerier_GetStagedItem_Call {
	_c.Call.Return(run)
	return _c
}

// ListPantryItems provides a mock function with given fields: ctx
func (_m *MockQuerier) ListPantryItems(ctx context.Context) ([]db.PantryItem, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPantryItems")
	}

	var r0 []db.PantryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]db.PantryItem, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []db.PantryItem); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.PantryItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_ListPantryItems_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPantryItems'
type MockQuerier_ListPantryItems_Call struct {
	*mock.Call
}

// ListPantryItems is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockQuerier_Expecter) ListPantryItems(ctx interface{}) *MockQuerier_ListPantryItems_Call {
	return &MockQuerier_ListPantryItems_Call{Call: _e.mock.On("ListPantryItems", ctx)}
}

func (_c *MockQuerier_ListPantryItems_Call) Run(run func(ctx context.Context)) *MockQuerier_ListPantryItems_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockQuerier_ListPantryItems_Call) Return(_a0 []db.PantryItem, _a1 error) *MockQuerier_ListPantryItems_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_ListPantryItems_Call) RunAndReturn(run func(context.Context) ([]db.PantryItem, error)) *MockQuerier_ListPantryItems_Call {
	_c.Call.Return(run)
	return _c
}

// ListStagedItemsByJob provides a mock function with given fields: ctx, jobID
func (_m *MockQuerier) ListStagedItemsByJob(ctx context.Context, jobID uuid.UUID) ([]db.StagedItem, error) {
	ret := _m.Called(ctx, jobID)

	if len(ret) == 0 {
		panic("no return value specified for ListStagedItemsByJob")
	}

	var r0 []db.StagedItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]db.StagedItem, error)); ok {
		return rf(ctx, jobID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []db.StagedItem); ok {
		r0 = rf(ctx, jobID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.StagedItem)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, jobID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_ListStagedItemsByJob_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStagedItemsByJob'
type MockQuerier_ListStagedItemsByJob_Call struct {
	*mock.Call
}

// ListStagedItemsByJob is a helper method to define mock.On call
//   - ctx context.Context
//   - jobID uuid.UUID
func (_e *MockQuerier_Expecter) ListStagedItemsByJob(ctx interface{}, jobID interface{}) *MockQuerier_ListStagedItemsByJob_Call {
	return &MockQuerier_ListStagedItemsByJob_Call{Call: _e.mock.On("ListStagedItemsByJob", ctx, jobID)}
}

func (_c *MockQuerier_ListStagedItemsByJob_Call) Run(run func(ctx context.Context, jobID uuid.UUID)) *MockQuerier_ListStagedItemsByJob_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockQuerier_ListStagedItemsByJob_Call) Return(_a0 []db.StagedItem, _a1 error) *MockQuerier_ListStagedItemsByJob_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_ListStagedItemsByJob_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]db.StagedItem, error)) *MockQuerier_ListStagedItemsByJob_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIngestionJobStatus provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateIngestionJobStatus(ctx context.Context, arg db.UpdateIngestionJobStatusParams) (db.IngestionJob, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateIngestionJobStatus")
	}

	var r0 db.IngestionJob
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateIngestionJobStatusParams) (db.IngestionJob, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateIngestionJobStatusParams) db.IngestionJob); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.IngestionJob)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateIngestionJobStatusParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_UpdateIngestionJobStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIngestionJobStatus'
type MockQuerier_UpdateIngestionJobStatus_Call struct {
	*mock.Call
}

// UpdateIngestionJobStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateIngestionJobStatusParams
func (_e *MockQuerier_Expecter) UpdateIngestionJobStatus(ctx interface{}, arg interface{}) *MockQuerier_UpdateIngestionJobStatus_Call {
	return &MockQuerier_UpdateIngestionJobStatus_Call{Call: _e.mock.On("UpdateIngestionJobStatus", ctx, arg)}
}

func (_c *MockQuerier_UpdateIngestionJobStatus_Call) Run(run func(ctx context.Context, arg db.UpdateIngestionJobStatusParams)) *MockQuerier_UpdateIngestionJobStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateIngestionJobStatusParams))
	})
	return _c
}

func (_c *MockQuerier_UpdateIngestionJobStatus_Call) Return(_a0 db.IngestionJob, _a1 error) *MockQuerier_UpdateIngestionJobStatus_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_UpdateIngestionJobStatus_Call) RunAndReturn(run func(context.Context, db.UpdateIngestionJobStatusParams) (db.IngestionJob, error)) *MockQuerier_UpdateIngestionJobStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStagedItem provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpdateStagedItem(ctx context.Context, arg db.UpdateStagedItemParams) (db.StagedItem, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStagedItem")
	}

	var r0 db.StagedItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateStagedItemParams) (db.StagedItem, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpdateStagedItemParams) db.StagedItem); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.StagedItem)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpdateStagedItemParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_UpdateStagedItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStagedItem'
type MockQuerier_UpdateStagedItem_Call struct {
	*mock.Call
}

// UpdateStagedItem is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpdateStagedItemParams
func (_e *MockQuerier_Expecter) UpdateStagedItem(ctx interface{}, arg interface{}) *MockQuerier_UpdateStagedItem_Call {
	return &MockQuerier_UpdateStagedItem_Call{Call: _e.mock.On("UpdateStagedItem", ctx, arg)}
}

func (_c *MockQuerier_UpdateStagedItem_Call) Run(run func(ctx context.Context, arg db.UpdateStagedItemParams)) *MockQuerier_UpdateStagedItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpdateStagedItemParams))
	})
	return _c
}

func (_c *MockQuerier_UpdateStagedItem_Call) Return(_a0 db.StagedItem, _a1 error) *MockQuerier_UpdateStagedItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_UpdateStagedItem_Call) RunAndReturn(run func(context.Context, db.UpdateStagedItemParams) (db.StagedItem, error)) *MockQuerier_UpdateStagedItem_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertPantryItem provides a mock function with given fields: ctx, arg
func (_m *MockQuerier) UpsertPantryItem(ctx context.Context, arg db.UpsertPantryItemParams) (db.PantryItem, error) {
	ret := _m.Called(ctx, arg)

	if len(ret) == 0 {
		panic("no return value specified for UpsertPantryItem")
	}

	var r0 db.PantryItem
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, db.UpsertPantryItemParams) (db.PantryItem, error)); ok {
		return rf(ctx, arg)
	}
	if rf, ok := ret.Get(0).(func(context.Context, db.UpsertPantryItemParams) db.PantryItem); ok {
		r0 = rf(ctx, arg)
	} else {
		r0 = ret.Get(0).(db.PantryItem)
	}

	if rf, ok := ret.Get(1).(func(context.Context, db.UpsertPantryItemParams) error); ok {
		r1 = rf(ctx, arg)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQuerier_UpsertPantryItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertPantryItem'
type MockQuerier_UpsertPantryItem_Call struct {
	*mock.Call
}

// UpsertPantryItem is a helper method to define mock.On call
//   - ctx context.Context
//   - arg db.UpsertPantryItemParams
func (_e *MockQuerier_Expecter) UpsertPantryItem(ctx interface{}, arg interface{}) *MockQuerier_UpsertPantryItem_Call {
	return &MockQuerier_UpsertPantryItem_Call{Call: _e.mock.On("UpsertPantryItem", ctx, arg)}
}

func (_c *MockQuerier_UpsertPantryItem_Call) Run(run func(ctx context.Context, arg db.UpsertPantryItemParams)) *MockQuerier_UpsertPantryItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(db.UpsertPantryItemParams))
	})
	return _c
}

func (_c *MockQuerier_UpsertPantryItem_Call) Return(_a0 db.PantryItem, _a1 error) *MockQuerier_UpsertPantryItem_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQuerier_UpsertPantryItem_Call) RunAndReturn(run func(context.Context, db.UpsertPantryItemParams) (db.PantryItem, error)) *MockQuerier_UpsertPantryItem_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQuerier creates a new instance of MockQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQuerier {
	mock := &MockQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
