version: 2

linters:
  enable:
    - errcheck

issues:
  exclude-rules:
    - linters:
        - errcheck
      text: '(?i)Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*print(f|ln)?|os\.(Un)?Setenv). is not checked'

    - path: _test\.go
      linters:
        - errcheck
