// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockLLMExtractor is an autogenerated mock type for the LLMExtractor type
type MockLLMExtractor struct {
	mock.Mock
}

type MockLLMExtractor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLLMExtractor) EXPECT() *MockLLMExtractor_Expecter {
	return &MockLLMExtractor_Expecter{mock: &_m.Mock}
}

// Extract provides a mock function with given fields: ctx, text
func (_m *MockLLMExtractor) Extract(ctx context.Context, text string) (*ExtractionResponse, error) {
	ret := _m.Called(ctx, text)

	if len(ret) == 0 {
		panic("no return value specified for Extract")
	}

	var r0 *ExtractionResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*ExtractionResponse, error)); ok {
		return rf(ctx, text)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *ExtractionResponse); ok {
		r0 = rf(ctx, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ExtractionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockLLMExtractor_Extract_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Extract'
type MockLLMExtractor_Extract_Call struct {
	*mock.Call
}

// Extract is a helper method to define mock.On call
//   - ctx context.Context
//   - text string
func (_e *MockLLMExtractor_Expecter) Extract(ctx interface{}, text interface{}) *MockLLMExtractor_Extract_Call {
	return &MockLLMExtractor_Extract_Call{Call: _e.mock.On("Extract", ctx, text)}
}

func (_c *MockLLMExtractor_Extract_Call) Run(run func(ctx context.Context, text string)) *MockLLMExtractor_Extract_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockLLMExtractor_Extract_Call) Return(_a0 *ExtractionResponse, _a1 error) *MockLLMExtractor_Extract_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockLLMExtractor_Extract_Call) RunAndReturn(run func(context.Context, string) (*ExtractionResponse, error)) *MockLLMExtractor_Extract_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockLLMExtractor creates a new instance of MockLLMExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLLMExtractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLLMExtractor {
	mock := &MockLLMExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
