// Code generated by mockery v2.53.5. DO NOT EDIT.

package service

import (
	context "context"

	clients "github.com/mwhite7112/woodpantry-pantry/internal/clients"
	mock "github.com/stretchr/testify/mock"
)

// MockDictionaryResolver is an autogenerated mock type for the DictionaryResolver type
type MockDictionaryResolver struct {
	mock.Mock
}

type MockDictionaryResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDictionaryResolver) EXPECT() *MockDictionaryResolver_Expecter {
	return &MockDictionaryResolver_Expecter{mock: &_m.Mock}
}

// Resolve provides a mock function with given fields: ctx, rawName
func (_m *MockDictionaryResolver) Resolve(ctx context.Context, rawName string) (clients.ResolveResult, error) {
	ret := _m.Called(ctx, rawName)

	if len(ret) == 0 {
		panic("no return value specified for Resolve")
	}

	var r0 clients.ResolveResult
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (clients.ResolveResult, error)); ok {
		return rf(ctx, rawName)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) clients.ResolveResult); ok {
		r0 = rf(ctx, rawName)
	} else {
		r0 = ret.Get(0).(clients.ResolveResult)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, rawName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDictionaryResolver_Resolve_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Resolve'
type MockDictionaryResolver_Resolve_Call struct {
	*mock.Call
}

// Resolve is a helper method to define mock.On call
//   - ctx context.Context
//   - rawName string
func (_e *MockDictionaryResolver_Expecter) Resolve(ctx interface{}, rawName interface{}) *MockDictionaryResolver_Resolve_Call {
	return &MockDictionaryResolver_Resolve_Call{Call: _e.mock.On("Resolve", ctx, rawName)}
}

func (_c *MockDictionaryResolver_Resolve_Call) Run(run func(ctx context.Context, rawName string)) *MockDictionaryResolver_Resolve_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockDictionaryResolver_Resolve_Call) Return(_a0 clients.ResolveResult, _a1 error) *MockDictionaryResolver_Resolve_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDictionaryResolver_Resolve_Call) RunAndReturn(run func(context.Context, string) (clients.ResolveResult, error)) *MockDictionaryResolver_Resolve_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockDictionaryResolver creates a new instance of MockDictionaryResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDictionaryResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDictionaryResolver {
	mock := &MockDictionaryResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
