// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ingestion_jobs.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createIngestionJob = `-- name: CreateIngestionJob :one
INSERT INTO ingestion_jobs (type, raw_input)
VALUES ($1, $2)
RETURNING id, type, raw_input, status, created_at
`

type CreateIngestionJobParams struct {
	Type     string
	RawInput string
}

func (q *Queries) CreateIngestionJob(ctx context.Context, arg CreateIngestionJobParams) (IngestionJob, error) {
	row := q.db.QueryRowContext(ctx, createIngestionJob, arg.Type, arg.RawInput)
	var i IngestionJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.RawInput,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const createStagedItem = `-- name: CreateStagedItem :one
INSERT INTO staged_items (job_id, ingredient_id, raw_text, quantity, unit, confidence, needs_review)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, job_id, ingredient_id, raw_text, quantity, unit, confidence, needs_review
`

type CreateStagedItemParams struct {
	JobID        uuid.UUID
	IngredientID uuid.NullUUID
	RawText      string
	Quantity     float64
	Unit         string
	Confidence   float64
	NeedsReview  bool
}

func (q *Queries) CreateStagedItem(ctx context.Context, arg CreateStagedItemParams) (StagedItem, error) {
	row := q.db.QueryRowContext(ctx, createStagedItem,
		arg.JobID,
		arg.IngredientID,
		arg.RawText,
		arg.Quantity,
		arg.Unit,
		arg.Confidence,
		arg.NeedsReview,
	)
	var i StagedItem
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.IngredientID,
		&i.RawText,
		&i.Quantity,
		&i.Unit,
		&i.Confidence,
		&i.NeedsReview,
	)
	return i, err
}

const getIngestionJob = `-- name: GetIngestionJob :one
SELECT id, type, raw_input, status, created_at
FROM ingestion_jobs
WHERE id = $1
`

func (q *Queries) GetIngestionJob(ctx context.Context, id uuid.UUID) (IngestionJob, error) {
	row := q.db.QueryRowContext(ctx, getIngestionJob, id)
	var i IngestionJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.RawInput,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getStagedItem = `-- name: GetStagedItem :one
SELECT id, job_id, ingredient_id, raw_text, quantity, unit, confidence, needs_review
FROM staged_items
WHERE id = $1
`

func (q *Queries) GetStagedItem(ctx context.Context, id uuid.UUID) (StagedItem, error) {
	row := q.db.QueryRowContext(ctx, getStagedItem, id)
	var i StagedItem
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.IngredientID,
		&i.RawText,
		&i.Quantity,
		&i.Unit,
		&i.Confidence,
		&i.NeedsReview,
	)
	return i, err
}

const listStagedItemsByJob = `-- name: ListStagedItemsByJob :many
SELECT id, job_id, ingredient_id, raw_text, quantity, unit, confidence, needs_review
FROM staged_items
WHERE job_id = $1
ORDER BY raw_text
`

func (q *Queries) ListStagedItemsByJob(ctx context.Context, jobID uuid.UUID) ([]StagedItem, error) {
	rows, err := q.db.QueryContext(ctx, listStagedItemsByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StagedItem
	for rows.Next() {
		var i StagedItem
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.IngredientID,
			&i.RawText,
			&i.Quantity,
			&i.Unit,
			&i.Confidence,
			&i.NeedsReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngestionJobStatus = `-- name: UpdateIngestionJobStatus :one
UPDATE ingestion_jobs
SET status = $2
WHERE id = $1
RETURNING id, type, raw_input, status, created_at
`

type UpdateIngestionJobStatusParams struct {
	ID     uuid.UUID
	Status string
}

func (q *Queries) UpdateIngestionJobStatus(ctx context.Context, arg UpdateIngestionJobStatusParams) (IngestionJob, error) {
	row := q.db.QueryRowContext(ctx, updateIngestionJobStatus, arg.ID, arg.Status)
	var i IngestionJob
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.RawInput,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateStagedItem = `-- name: UpdateStagedItem :one
UPDATE staged_items
SET ingredient_id = $2,
    quantity      = $3,
    unit          = $4
WHERE id = $1
RETURNING id, job_id, ingredient_id, raw_text, quantity, unit, confidence, needs_review
`

type UpdateStagedItemParams struct {
	ID           uuid.UUID
	IngredientID uuid.NullUUID
	Quantity     float64
	Unit         string
}

func (q *Queries) UpdateStagedItem(ctx context.Context, arg UpdateStagedItemParams) (StagedItem, error) {
	row := q.db.QueryRowContext(ctx, updateStagedItem,
		arg.ID,
		arg.IngredientID,
		arg.Quantity,
		arg.Unit,
	)
	var i StagedItem
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.IngredientID,
		&i.RawText,
		&i.Quantity,
		&i.Unit,
		&i.Confidence,
		&i.NeedsReview,
	)
	return i, err
}
