// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type IngestionJob struct {
	ID        uuid.UUID
	Type      string
	RawInput  string
	Status    string
	CreatedAt time.Time
}

type PantryItem struct {
	ID           uuid.UUID
	IngredientID uuid.UUID
	Quantity     float64
	Unit         string
	ExpiresAt    sql.NullTime
	AddedAt      time.Time
	UpdatedAt    time.Time
}

type StagedItem struct {
	ID           uuid.UUID
	JobID        uuid.UUID
	IngredientID uuid.NullUUID
	RawText      string
	Quantity     float64
	Unit         string
	Confidence   float64
	NeedsReview  bool
}
