// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: pantry_items.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const deleteAllPantryItems = `-- name: DeleteAllPantryItems :exec
DELETE FROM pantry_items
`

func (q *Queries) DeleteAllPantryItems(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAllPantryItems)
	return err
}

const deletePantryItem = `-- name: DeletePantryItem :exec
DELETE FROM pantry_items WHERE id = $1
`

func (q *Queries) DeletePantryItem(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deletePantryItem, id)
	return err
}

const getPantryItem = `-- name: GetPantryItem :one
SELECT id, ingredient_id, quantity, unit, expires_at, added_at, updated_at
FROM pantry_items
WHERE id = $1
`

func (q *Queries) GetPantryItem(ctx context.Context, id uuid.UUID) (PantryItem, error) {
	row := q.db.QueryRowContext(ctx, getPantryItem, id)
	var i PantryItem
	err := row.Scan(
		&i.ID,
		&i.IngredientID,
		&i.Quantity,
		&i.Unit,
		&i.ExpiresAt,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPantryItems = `-- name: ListPantryItems :many
SELECT id, ingredient_id, quantity, unit, expires_at, added_at, updated_at
FROM pantry_items
ORDER BY added_at
`

func (q *Queries) ListPantryItems(ctx context.Context) ([]PantryItem, error) {
	rows, err := q.db.QueryContext(ctx, listPantryItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PantryItem
	for rows.Next() {
		var i PantryItem
		if err := rows.Scan(
			&i.ID,
			&i.IngredientID,
			&i.Quantity,
			&i.Unit,
			&i.ExpiresAt,
			&i.AddedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPantryItem = `-- name: UpsertPantryItem :one
INSERT INTO pantry_items (ingredient_id, quantity, unit, expires_at)
VALUES ($1, $2, $3, $4)
ON CONFLICT (ingredient_id) DO UPDATE
  SET quantity   = EXCLUDED.quantity,
      unit       = EXCLUDED.unit,
      expires_at = EXCLUDED.expires_at,
      updated_at = now()
RETURNING id, ingredient_id, quantity, unit, expires_at, added_at, updated_at
`

type UpsertPantryItemParams struct {
	IngredientID uuid.UUID
	Quantity     float64
	Unit         string
	ExpiresAt    sql.NullTime
}

func (q *Queries) UpsertPantryItem(ctx context.Context, arg UpsertPantryItemParams) (PantryItem, error) {
	row := q.db.QueryRowContext(ctx, upsertPantryItem,
		arg.IngredientID,
		arg.Quantity,
		arg.Unit,
		arg.ExpiresAt,
	)
	var i PantryItem
	err := row.Scan(
		&i.ID,
		&i.IngredientID,
		&i.Quantity,
		&i.Unit,
		&i.ExpiresAt,
		&i.AddedAt,
		&i.UpdatedAt,
	)
	return i, err
}
