// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateIngestionJob(ctx context.Context, arg CreateIngestionJobParams) (IngestionJob, error)
	CreateStagedItem(ctx context.Context, arg CreateStagedItemParams) (StagedItem, error)
	DeleteAllPantryItems(ctx context.Context) error
	DeletePantryItem(ctx context.Context, id uuid.UUID) error
	GetIngestionJob(ctx context.Context, id uuid.UUID) (IngestionJob, error)
	GetPantryItem(ctx context.Context, id uuid.UUID) (PantryItem, error)
	GetStagedItem(ctx context.Context, id uuid.UUID) (StagedItem, error)
	ListPantryItems(ctx context.Context) ([]PantryItem, error)
	ListStagedItemsByJob(ctx context.Context, jobID uuid.UUID) ([]StagedItem, error)
	UpdateIngestionJobStatus(ctx context.Context, arg UpdateIngestionJobStatusParams) (IngestionJob, error)
	UpdateStagedItem(ctx context.Context, arg UpdateStagedItemParams) (StagedItem, error)
	UpsertPantryItem(ctx context.Context, arg UpsertPantryItemParams) (PantryItem, error)
}

var _ Querier = (*Queries)(nil)
